const ESTADOS = {
    CREADO: "CREADO",
    EN_PROCESO: "EN PROCESO",
    FINALIZADO: "FINALIZADO",
    A_DETERMINAR: "A DETERMINAR",
  }

const DETALLES = {
  SERVICIO_TECNICO: "SERVICIO TECNICO",
  ACCESORIOS: "ACCESORIOS",
  ASIGNACION: "ASIGNACION",
  EXTRAVIO: "EXTRAVIO",
  EXTRAVIO_A_VERIFICAR: "EXTRAVIO A VERIFICAR",
  PERITAJE: "PERITAJE",
}

export {ESTADOS, DETALLES}; 