const ESTADOS = {
    CREADO: "Creado",
    EN_PROCESO: "En Proceso",
    FINALIZADO: "Finalizado",
    A_DETERMINAR: "A Determinar",
  }

const DETALLES = {
  SERVICIO_TECNICO: "SERVICIO TECNICO",
  ACCESORIOS: "ACCESORIOS",
  ASIGNACION: "ASIGNACION",
  EXTRAVIO: "EXTRAVIO",
  EXTRAVIO_A_VERIFICAR: "EXTRAVIO A VERIFICAR",
  PERITAJE: "PERITAJE",
}

export {ESTADOS, DETALLES}; 